application: knightso-589
version: 3
runtime: python27
api_version: 1
threadsafe: yes
default_expiration: "1h"

handlers:
- url: /
  static_files: html/index.html
  upload: html/index.html

- url: /(.*)
  static_files: html/\1
  upload: html/.*

libraries:
- name: webapp2
  version: "2.5.2"
