runtime: python27
api_version: 1
threadsafe: yes
default_expiration: "1h"

handlers:
- url: /
  static_files: html/index.html
  upload: html/index.html
  secure: always

- url: /5mingcp/
  static_files: html/5mingcp/index.html
  upload: html/5mingcp/index.html
  secure: always

- url: /(.*)
  static_files: html/\1
  upload: html/.*
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"

